services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: nexus_forge
      DB_MIGRATIONS_RUN: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NATS_SERVERS: nats://nats:4222
      JWT_SECRET: change-me
      JWT_EXPIRES_IN_SECONDS: 3600
      JWT_REFRESH_SECRET: change-me-refresh
      JWT_REFRESH_EXPIRES_IN_SECONDS: 604800
      OUTBOX_POLL_INTERVAL_MS: 1500
      OUTBOX_MAX_ATTEMPTS: 5
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - nats

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexus_forge
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nats:
    image: nats:2.10-alpine
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"

  swagger:
    image: swaggerapi/swagger-ui:v5.30.1
    environment:
      URL: http://localhost:3000/api/docs-json
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  pg_data:
